//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class modelo1Container : DbContext
    {
        public modelo1Container()
            : base("name=modelo1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleados> EmpleadosSet { get; set; }
        public virtual DbSet<Departamentos> DepartamentosSet { get; set; }
        public virtual DbSet<Cargos> CargosSet { get; set; }
        public virtual DbSet<CalculoDeNomina> CalculoDeNominaSet { get; set; }
        public virtual DbSet<SalidaDEmpleados> SalidaDEmpleadosSet { get; set; }
        public virtual DbSet<Vacaciones> VacacionesSet { get; set; }
        public virtual DbSet<Permisos> PermisosSet { get; set; }
        public virtual DbSet<Licencias> LicenciasSet { get; set; }
    }
}
